name: Run Flake Linting
on:
  pull_request:
  push:
permissions:
  contents: read

jobs:
  fmt:
    name: Run formatters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - name: Flake check
        run: nix fmt
  check:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `nix flake show`
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - name: Build
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install -U pip --group build
          python setup.py build -v
      - name: Flake check
        run: |
          nix flake check
